api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        versions: [3]
    enable_swagger_ui: true

    enable_re_doc: true
    enable_docs: true
    title: 'API specification'
    description: 'summer house API specification 😇😇'
    version: '1.0.0'
