security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
      app_user_provider:
        entity:
          class: App\Entity\User
          property: phoneNumber

    firewalls:
      main:
        lazy: true
        provider: app_user_provider
        pattern: 
          ^/
        form_login:
          login_path: app_login
          check_path: app_login
          enable_csrf: true
        logout:
          path: app_logout
          # where to redirect after logout
          # target: app_any_route


    access_control:
      - { path: ^/login$, roles: PUBLIC_ACCESS }
      - { path: ^/user$,  roles: PUBLIC_ACCESS }
      - { path: ^/, roles: IS_AUTHENTICATED_FULLY }