services:
  php:
      build: 
        context: ./docker/php
      container_name: php-container
      ports:
          - "9000:9000"
      volumes:
          - .:/var/www/project
      restart: always
  nginx:
      build: 
        context: ./docker/nginx
      container_name: nginx-container
      volumes:
        - .:/var/www/project
      ports:
        - "8080:80"
      depends_on:
        - php
        - db

  db:
    build:
      context: ./docker/postgresql
    container_name: db-container