controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


app_get_user_by_id: 
  path: /user/{id}
  controller: App\Controller\UserController::getOneUser
  methods: [GET]

app_create_user: 
  path: /user
  controller: App\Controller\UserController::createUser
  methods: [POST]

app_get_all_users: 
  path: /user
  controller: App\Controller\UserController::getAllUsers
  methods: [GET]

app_get_all_summer_houses: 
  path: /summer-house 
  controller: App\Controller\SummerHouseController::getAll
  methods: [GET]


app_get_summer_house: 
  path: /summer-house/{id}
  controller: App\Controller\SummerHouseController::getById
  methods: [GET]

app_create_summer_house: 
  path: /summer-house
  controller: App\Controller\SummerHouseController::create
  methods: [POST]

app_create_request: 
  path: /request
  controller: App\Controller\RequestController::createRequest 
  methods: [POST]

app_fully_change_request: 
  path: /request
  controller: App\Controller\RequestController::changeRequest
  methods: [PUT]

app_change_request_commit: 
  path: /request
  controller: App\Controller\RequestController::changeRequestComment
  methods: [PATCH]
