controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_get_all_summer_houses: 
  path: /house 
  controller: App\Controller\SummerHouseController::getAll
  methods: [GET]
  
app_create_request: 
  path: /request
  controller: App\Controller\RequestController::createRequest 
  methods: [POST]

app_fully_change_request: 
  path: /request
  controller: App\Controller\RequestController::changeRequest
  methods: [PUT]

app_change_request_commit: 
  path: /request
  controller: App\Controller\RequestController::changeRequestComment
  methods: [PATCH]
